<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="row gutters-sm">
                        <div class="col-md-4 d-none d-md-block">
                            <div class="card">
                                <div class="card-body">
                                    <nav class="nav flex-column nav-pills nav-gap-y-1">
                                        <a href="#profile" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded active">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user mr-2">
                                                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                                <circle cx="12" cy="7" r="4"></circle>
                                            </svg>Profile Information
                                        </a>
                                        <a href="#account" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings mr-2">
                                                <circle cx="12" cy="12" r="3"></circle>
                                                <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
                                            </svg>Configuracion de la cuenta
                                        </a>
                                        <a href="#security" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shield mr-2">
                                                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                                            </svg>Seguridad
                                        </a>


                                    </nav>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card">
                                <div class="card-header border-bottom mb-3 d-flex d-md-none">
                                    <ul class="nav nav-tabs card-header-tabs nav-gap-x-1" role="tablist">
                                        <li class="nav-item">
                                            <a href="#profile" data-toggle="tab" class="nav-link has-icon active"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
                                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                                    <circle cx="12" cy="7" r="4"></circle>
                                                </svg></a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#account" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings">
                                                    <circle cx="12" cy="12" r="3"></circle>
                                                    <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
                                                </svg></a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#security" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shield">
                                                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                                                </svg></a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#notification" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell">
                                                    <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                                                    <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                                                </svg></a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#billing" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-credit-card">
                                                    <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
                                                    <line x1="1" y1="10" x2="23" y2="10"></line>
                                                </svg></a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="card-body tab-content">
                                    <div class="tab-pane active" id="profile">
                                        <h6>SU INFORMACION DE PERFIL</h6>
                                        <hr>
                                        <form>
                                            <div class="form-group">
                                                <label for="fullName">Nombre Completo</label>
                                                <input type="text" class="form-control" id="fullName" aria-describedby="fullNameHelp" placeholder="Este es su Nombre Completo" readonly>
                                                <small id="fullNameHelp" class="form-text text-muted">Su nombre puede aparecer por aquí donde se le menciona. Puede cambiarlo o eliminarlo en cualquier momento.</small>
                                            </div>
                                            <div class="form-group">
                                                <label for="name">Nombre</label>
                                                <input type="text" name="name" class="form-control" id="name" placeholder="Ingrese su Nombre">
                                            </div>
                                            <div class="form-group">
                                                <label for="apellido">Apellido</label>
                                                <input type="text" class="form-control" id="url" placeholder="Ingrese su Apellido">
                                            </div>
                                            <div class="form-group">
                                                <label for="location">Ubicacion</label>
                                                <input type="text" class="form-control" id="location" placeholder="Ingrese su Ubicacion" value="Bay Area, San Francisco, CA">
                                            </div>
                                            <div class="form-group small text-muted">
                                                Todos los campos de esta página son opcionales y se pueden eliminar en cualquier momento, y al completarlos, nos da su consentimiento para compartir estos datos dondequiera que aparezca su perfil de usuario.
                                            </div>
                                            <button type="button" class="btn btn-primary">Actualizar Perfil</button>

                                        </form>
                                    </div>
                                    <div class="tab-pane" id="account">
                                        <h6>CONFIGURACION DE LA CUENTA</h6>
                                        <hr>
                                        <form>
                                            <div class="form-group">
                                                <label for="username">Nombre de Usuario</label>
                                                <input type="text" class="form-control" id="username" aria-describedby="usernameHelp" placeholder="Ingrese su Nombre de Usuario" value="kennethvaldez">
                                                <small id="usernameHelp" class="form-text text-muted">Después de cambiar su nombre de usuario, su antiguo nombre de usuario estará disponible para que cualquier otra persona lo reclame.</small>
                                            </div>
                                            <hr>
                                            <div class="form-group">
                                                <select name="" id="" class="form-control">
                                                    <option selected>Seleccione idioma</option>
                                                    <option value="1">Español</option>
                                                    <option value="2">Ingles</option>
                                                   
                                                </select>
                                            </div>
                                            <hr>
                                            <div class="form-group">
                                                <label class="d-block text-danger">Eliminar Cuenta</label>
                                                <p class="text-muted font-size-sm">Una vez que elimine su cuenta, no hay vuelta atrás. Por favor, tenga la certeza..</p>
                                            </div>
                                            <button class="btn btn-danger" type="button">Eliminar Cuenta</button>

                                        </form>
                                    </div>
                                    <div class="tab-pane" id="security">
                                        <h6>CONFIGURACIONES DE SEGURIDAD</h6>
                                        <hr>
                                        <form>
                                            <div class="form-group">
                                                <label class="d-block">Cambiar la contraseña</label>
                                                <input type="password" class="form-control" placeholder="Ingrese su contraseña anterior">
                                                <input type="password" class="form-control mt-1" placeholder="Nueva Contraseña">
                                                <input type="password" class="form-control mt-1" placeholder="Confirmar nueva contraseña">
                                            </div>
                                            <button class="btn btn-primary" type="button">Actualizar Contraseña</button>
                                        </form>

                                        <hr>
                                        <form>
                                            <div class="form-group mb-0">
                                                <label class="d-block">Sessions</label>
                                                <p class="font-size-sm text-secondary">Esta es una lista de dispositivos que han iniciado sesión en su cuenta. Revoque las sesiones que no reconozca.</p>
                                                <ul class="list-group list-group-sm">
                                                    <li class="list-group-item has-icon">
                                                        <div>
                                                            <h6 class="mb-0">San Francisco City 190.24.335.55</h6>
                                                            <small class="text-muted">Your current session seen in United States</small>
                                                        </div>
                                                        <button class="btn btn-light btn-sm ml-auto" type="button">More info</button>
                                                    </li>
                                                </ul>
                                            </div>
                                        </form>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->