<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
<?php require_once "app/master/views/template/sidebar.phtml"; ?>

        
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="wrapper-chat">
                        <section class="chat-area">
                            <header> 
                                <a href="?controller=salasdechat" class="back-icon"><i class="fas fa-arrow-left"></i></a>
                                <img src="http://localhost/chat/modelo/images/1638457284Profile%20github.png" alt="">
                                <div class="details">
                                    <span>YEIMAR LEMUS</span>
                                    <p>Activo Ahora</p>
                                </div>
                            </header>
                            <div class="chat-box">

                            </div>
                            <form action="#" class="typing-area">
                                <input type="text" class="incoming_id" name="incoming_id" value="2345678" hidden>
                                <input type="text" name="message" class="input-field" placeholder="Escribe un mensaje aquí ..." autocomplete="off">
                                <button><i class="fab fa-telegram-plane"></i></button>
                            </form>
                        </section>
                    </div>
                    
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->