<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.phtml"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.phtml"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4 wrapper border-bottom-info">
                        <div class="card-header py-3 wrapper">
                            <h6 class="m-0 font-weight-bold text-primary">Copias de Seguridad<button class="btn btn-sm btn-info" data-toggle="modal" data-target="#Add-Backup" type="button" ><i class="fas fa-history" aria-hidden="true"></i> </button></h6>
                        </div>
                        <div class="card-body ">
                            <div class="table-responsive">
                                <table class="table table-bordered" width="100%" cellspacing="0" id="TablaBackups">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nombre</th>
                                            <th>Tamaño</th>
                                            
                                            <th>Fecha</th>
                                            <th>Usuario</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <td></td>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- Modal Formulario Acces Token-->
                    <div class="modal fade " id="Add-Backup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog " role="document">
                            <div class="modal-content wrapper border-bottom-warning">
                                <div class="modal-header" style="background-color: #4281A4; color: white">
                                    <h2 class="modal-title " id="exampleModalLongTitle">Crear Respaldo<i class="fas fa-database"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <section>
                                    <div>
                                        <!--Formulario-->
                                        <form method="POST" class="row g-3 needs-validation col" id="frmAccesWebToken">
                                            <div class="col-12 col-md-12">
                                                <label for="nombre">Nombre</label>.
                                                <input type="text" name="nombre" id="nombre" class="form-control" placeholder="ejemplo: respaldo-1" required="">
                                            </div>
                                            <div class="col-12 col-md-12">
                                                <label for="descripcion">Descripccion</label>
                                                <input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="ejemplo: Base de datosdel dia 1" required="">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" name="btnIngresoAccesWebToken" class="btn btn-info" id="btnIngresoAccesWebToken"><i class="fas fa-sync"></i> Crear</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cerrar</button>
                                            </div>

                                        </form>

                                    </div>

                                </section>

                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->