<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper">

		<?php require_once "app/master/views/template/sidebar.html"; ?>

		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<?php require_once "app/master/views/template/navbar.html"; ?>

				<!-- Begin Page Content -->
				<div class="container-fluid">

					<div class="container">
						<div class="row">
							<div class="col-lg-11 my-1">
								<div class="card rounded-0">
									<div class="card-body">

										<section>

											<div class="wrapper">
												<section class="users">
													<header>
														<div class="content">

															<img src="https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg" width="200" />


															<div class="details">
																<span>MASTER</span>
																<p>Activo</p>
															</div>
														</div>
													</header>
													<div class="search">
														<span class="text">Seleccione un usuario para iniciar el chat</span>
														<input type="text" placeholder="Ingrese el nombre para buscar ...">
														<button><i class="fas fa-search"></i></button>
													</div>
													<div class="users-list" id="tbody">
														<center>
														<div class="spinner-grow text-info" role="status">
															<span class="visually-hidden"></span>
														</div>
														</center>
														
													</div>
												</section>
											</div>

										</section>


									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
				<!-- /.container-fluid -->

			</div>
			<!-- End of Main Content -->