<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.phtml"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.phtml"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <h1>Modulo en Construccion</h1>

                </div>
                <!-- End of Main Content -->