<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.phtml"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.phtml"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4 wrapper border-bottom-primary">
                        <div class="card-header py-3 wrapper">
                            <h6 class="m-0 font-weight-bold text-primary">Usuarios - Agentes <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#Add-agentes" type="button"><i class="fas fa-plus-circle" aria-hidden="true"></i> Nuevo</button></h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="TablaAgentes">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Usuario</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Documento</th>
                                            <th>Telefono</th>
                                            <th>Correo</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <td></td>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- Modal Agregar Usuarios -->
                    <div class="modal fade" id="Add-agentes" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content wrapper border-bottom-warning">
                                <div class="modal-header" style="background-color: #F7A83B; color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Nuevo Usuario <i class="fa fa-user-plus" aria-hidden="true"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form id="formAgregarUsuarios" method="POST" name="formAgregarUsuarios" class="formHorizontal">
                                        <input type="hidden" id="idUsuario" name="idUsuario" value="">

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="usuario">Usuario</label>
                                                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="ejemplo: @user" required="">
                                            </div>

                                            <div class="form-group col-md-6">

                                                <label for="documento">Documento</label>
                                                <input type="text" class="form-control" id="documento" name="documento" placeholder="" required="">

                                            </div>


                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="nombre">Nombre</label>
                                                <input type="text" class="form-control valid validText" id="nombre" name="nombre" required="">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="apellido">Apellidos</label>
                                                <input type="text" class="form-control valid validText" id="apellido" name="apellido" required="">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="telefono">Telefono</label>
                                                <input type="text" class="form-control valid validNumber" id="telefono" name="telefono" required="">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="email">Email</label>
                                                <input type="text" class="form-control valid validEmail" id="email" name="email" required="">
                                            </div>
                                        </div>

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="password">Password</label>
                                                <input type="password" class="form-control" id="password" name="password" autocomplete="on">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="confirmpassword">Confirmar contraseña</label>
                                                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" autocomplete="on">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="direccion">Direccion</label>
                                                <input type="text" class="form-control" id="direccion" name="direccion" required>
                                            </div>
                                            <div class="form-check form-switch col-md-6">
                                                <label for="rol">Rol usuario</label>
                                                <div class="form-check form-switch">
                                                    <input class="form-check-input" type="checkbox" name="master" id="master" >
                                                    <label class="form-check-label" for="master">Master</label>
                                                </div>
                                                <div class="form-check form-switch">
                                                    <input class="form-check-input" type="checkbox" name="admin" id="admin" data-role="flipswitch" >
                                                    <label class="form-check-label" for="admin">Admin</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tile-footer">
                                            <button id="btnActionForm" class="btn btn-success" type="button"><i class="fa fa-fw fa-lg fa-check-circle" aria-hidden="true"></i><span id="btnText">Registrar</span></button>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <button class="btn btn-danger" type="button" data-dismiss="modal"><i class="fa fa-fw fa-lg fa-check-circle"></i> Cerrar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal Editar Usuarios -->
                    <!-- modalUsuarios -->
                    <div class="modal fade" id="Edit-agentes" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content wrapper border-bottom-warning">
                                <div class="modal-header" style="background-color: #35A7FF; color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Actualizar Usuarios <i class="fas fa-user-edit" aria-hidden="true"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form id="formAgregarUsuarios" method="POST" name="formAgregarUsuarios" class="formHorizontal">
                                        <input type="hidden" id="idUsuario" name="idUsuario" value="">

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="usuario">Usuario</label>
                                                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="ejemplo: @user" required="">
                                            </div>

                                            <div class="form-group col-md-6">

                                                <label for="documento">Documento</label>
                                                <input type="text" class="form-control" id="documento" name="documento" placeholder="" required="">

                                            </div>


                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="nombre">Nombre</label>
                                                <input type="text" class="form-control valid validText" id="nombre" name="nombre" required="">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="apellido">Apellidos</label>
                                                <input type="text" class="form-control valid validText" id="apellido" name="apellido" required="">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="telefono">Telefono</label>
                                                <input type="text" class="form-control valid validNumber" id="telefono" name="telefono" required="">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="email">Email</label>
                                                <input type="text" class="form-control valid validEmail" id="email" name="email" required="">
                                            </div>
                                        </div>

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="password">Password</label>
                                                <input type="password" class="form-control" id="password" name="password" autocomplete="on">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="confirmpassword">Confirmar contraseña</label>
                                                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" autocomplete="on">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="direccion">Direccion</label>
                                                <input type="text" class="form-control" id="direccion" name="direccion" required>
                                            </div>
                                            <div class="form-check form-switch col-md-6">
                                                <label for="rol">Rol usuario</label>
                                                <div class="form-check form-switch">
                                                    <input class="form-check-input" type="checkbox" name="master" id="master" >
                                                    <label class="form-check-label" for="master">Master</label>
                                                </div>
                                                <div class="form-check form-switch">
                                                    <input class="form-check-input" type="checkbox" name="admin" id="admin" data-role="flipswitch" >
                                                    <label class="form-check-label" for="admin">Admin</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tile-footer">
                                            <button id="btnActionForm" class="btn btn-success" type="button"><i class="fa fa-fw fa-lg fa-check-circle" aria-hidden="true"></i><span id="btnText">Registrar</span></button>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <button class="btn btn-danger" type="button" data-dismiss="modal"><i class="fa fa-fw fa-lg fa-check-circle"></i> Cerrar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    




                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->