<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4 wrapper">
                        <div class="card-header py-3 wrapper">
                            <h6 class="m-0 font-weight-bold text-primary">Usuarios - Agentes <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#Add-agentes" type="button"><i class="fas fa-plus-circle" aria-hidden="true"></i> Nuevo</button></h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered"  id="TablaAgentes">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Usuario</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Password</th>
                                            <th>Documento</th>
                                            <th>Telefono</th>
                                            <th>Correo</th>
                                            <th>Admin</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <td></td>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- modalUsuarios -->
                    <div class="modal fade" id="Add-agentes" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color: #F7A83B; color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Nuevo Usuario <i class="fa fa-user-plus" aria-hidden="true"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form id="formUsuario" name="formUsuario" class="formHorizontal">
                                        <input type="hidden" id="idUsuario" name="idUsuario" value="">

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="txtIdentificacion">Usuario</label>
                                                <input type="text" class="form-control" id="txtIdentificacion" name="txtIdentificacion" placeholder="ejemplo: @user" required="">
                                            </div>

                                            <div class="form-group col-md-6">

                                                <label for="documento">Documento</label>
                                                <input type="text" class="form-control" id="documento" name="documento" placeholder="" required="">

                                            </div>


                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="txtNombre">Nombres</label>
                                                <input type="text" class="form-control valid validText" id="txtNombre" name="txtNombre" required="">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="txtApellido">Apellidos</label>
                                                <input type="text" class="form-control valid validText" id="txtApellido" name="txtApellido" required="">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="txtTelefono">Telefono</label>
                                                <input type="text" class="form-control valid validNumber" id="txtTelefono" name="txtTelefono" required="" onkeypress="return controlTag(event);">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="txtEmail">Email</label>
                                                <input type="text" class="form-control valid validEmail" id="txtEmail" name="txtEmail" required="">
                                            </div>
                                        </div>

                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="txtPassword">Password</label>
                                                <input type="password" class="form-control" id="txtPassword" name="txtPassword">
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="repeatpassword">Confirmar contraseña</label>
                                                <input type="password" class="form-control" id="repeatPassword" name="repeatPassword">
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-6">
                                                <label for="txtPassword">Direccion</label>
                                                <input type="text" class="form-control" id="direcciond" name="direccion">
                                            </div>
                                            <div class="form-group col-md-6">
                                            <label for="txtrol">Rol usuario</label>
                                              <select class="form-control" name="txtrol" id="txtrol" ></select>
                                            </div>
                                        </div>




                                        <div class="tile-footer">
                                            <button id="btnActionForm" class="btn btn-success" type="submit"><i class="fa fa-fw fa-lg fa-check-circle" aria-hidden="true"></i><span id="btnText">Guardar</span></button>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <button class="btn btn-danger" type="button" data-dismiss="modal"><i class="fa fa-fw fa-lg fa-check-circle"></i> Cerrar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- modalViewUser -->
                    <div class="modal fade " id="modalViewUser" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content wrapper">
                                <div class="modal-header header-primary">
                                    <h5 class="modal-title" id="titleModal">Datos del usuario</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td>Identificación:</td>
                                                <td id="celIdentificacion">654654654</td>
                                            </tr>
                                            <tr>
                                                <td>Nombres:</td>
                                                <td id="celNombre">Jacob</td>
                                            </tr>
                                            <tr>
                                                <td>Apellidos:</td>
                                                <td id="celApellido">Jacob</td>
                                            </tr>
                                            <tr>
                                                <td>Teléfono:</td>
                                                <td id="celTelefono">Larry</td>
                                            </tr>
                                            <tr>
                                                <td>Email (Usuario):</td>
                                                <td id="celEmail">Larry</td>
                                            </tr>
                                            <tr>
                                                <td>Tipo Usuario:</td>
                                                <td id="celTipoUsuario">Larry</td>
                                            </tr>
                                            <tr>
                                                <td>Estado:</td>
                                                <td id="celEstado">Larry</td>
                                            </tr>
                                            <tr>
                                                <td>Fecha registro:</td>
                                                <td id="celFechaRegistro">Larry</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>




                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->