<div class="offcanvas offcanvas-start text-center my-5" tabindex="-1" id="Conversaciones" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <div class="container-fluid">
            <div class="row">
                <center>
                    <h3><i>Select Insurance</i></h3>
                </center>
            </div>
            <div class="row">
                <div class="col-12">
                    <form id="frmFiltroDialogNav">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="filtrarNav" id="filtrarNav" placeholder="Usuario" autocomplete="off">
                            <label for="filtrarNav"><i class="fas fa-search"></i> Filtrar</label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="offcanvas-body ScrollMinimo shadow border" id="tbodySala">

        <div class="spinner-grow text-info" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>

    </div>
</div>