<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">


                    <br>
                    <div class="section_our_solution">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="our_solution_category">
                                    <div class="solution_cards_box">
                                        <div class="solution_card">
                                            <div class="hover_color_bubble"></div>
                                            <div class="so_top_icon">
                                                <img src="https://img.icons8.com/color/144/000000/whatsapp--v3.gif" />
                                            </div>
                                            <div class="solu_title">
                                                <h3>Agregar Whatsapp</h3>
                                            </div>
                                            <div class="solu_description">
                                                <p>
                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                                                </p>
                                                <button type="button" class="read_more_btn" data-toggle="modal" data-target="#Add-phone-whatsapp">Add+</button>
                                            </div>
                                        </div>
                                        <div class="solution_card">
                                            <div class="hover_color_bubble"></div>
                                            <div class="so_top_icon">
                                                <img src="https://img.icons8.com/color/144/000000/chat--v3.gif" />
                                            </div>
                                            <div class="solu_title">
                                                <h3>Crear Plantillas de Mensajes</h3>
                                            </div>
                                            <div class="solu_description">
                                                <p>
                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                                                </p>
                                                <button type="button" class="read_more_btn" class="read_more_btn" data-toggle="modal" data-target="#Add-messagess-template">Add+</button>
                                            </div>
                                        </div>
                                    </div>
                                    <!--  -->
                                    <div class="solution_cards_box sol_card_top_3">
                                        <div class="solution_card">
                                            <div class="hover_color_bubble"></div>
                                            <div class="so_top_icon">
                                                <img src="https://img.icons8.com/material-sharp/384/000000/key--v2.gif" />
                                            </div>
                                            <div class="solu_title">
                                                <h3>Agregar Web Token</h3>
                                            </div>
                                            <div class="solu_description">
                                                <p>
                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                                                </p>
                                                <button type="button" class="read_more_btn" class="read_more_btn" data-toggle="modal" data-target="#Add-access-tokens">Add+</button>
                                            </div>
                                        </div>
                                        <div class="solution_card">
                                            <div class="hover_color_bubble"></div>
                                            <div class="so_top_icon">
                                                <img src="https://img.icons8.com/dusk/512/000000/bot--v2.gif" />
                                            </div>
                                            <div class="solu_title">
                                                <h3>Chat Bot</h3>
                                            </div>
                                            <div class="solu_description">
                                                <p>
                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                                                </p>
                                                <button type="button" class="read_more_btn">Read More</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Modal Formulario Whatsapp-->

                    <div class="modal fade" id="Add-phone-whatsapp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color: rgb(18, 140, 126); color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Agregar Whatsaap <i class="fab fa-whatsapp"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <section>
                                    <div>
                                        <!--Formulario-->
                                        <form action="?controller=AbrirSalaChat" method="POST" class="row g-3 needs-validation col" id="Formulario">
                                            <div class="col-12 col-md-6">
                                                <label for="codigopais">Codigo de Pais</label>
                                                <select name="codigopais" id="codigopais" ">
                                                    <option value=" 93">Afganistán</option>
                                                    <option value="355">Albania</option>
                                                    <option value="213">Argelia</option>
                                                    <option value="1(684)">Samoa Americana</option>
                                                    <option value="376">Andorra</option>
                                                    <option value="244">Angola</option>
                                                    <option value="1(264)">Anguila</option>
                                                    <option value="1(268)">Antigua y Barbuda</option>
                                                    <option value="54">Argentina</option>
                                                    <option value="374">Armenia</option>
                                                    <option value="297">Aruba</option>
                                                    <option value="61">Australia</option>
                                                    <option value="672">Territorio australiano</option>
                                                    <option value="43">Austria</option>
                                                    <option value="994">Azerbaiyán</option>
                                                    <option value="1(242)">Bahamas</option>
                                                    <option value="973">Bahrain</option>
                                                    <option value="880">Bangladesh</option>
                                                    <option value="1(246)">Barbados</option>
                                                    <option value="375">Belarus</option>
                                                    <option value="32">Bélgica</option>
                                                    <option value="501">Belice</option>
                                                    <option value="229">Benín</option>
                                                    <option value="1(441)">Bermuda</option>
                                                    <option value="975">Bután</option>
                                                    <option value="591">Bolivia</option>
                                                    <option value="387">Bosnia/Herzegovina</option>
                                                    <option value="267">Botsuana</option>
                                                    <option value="55">Brasil</option>
                                                    <option value="1(284)">Islas Vírgenes Británicas</option>
                                                    <option value="673">Brunéi</option>
                                                    <option value="359">Bulgaria</option>
                                                    <option value="226">Burkina Faso</option>
                                                    <option value="257">Burundi</option>
                                                    <option value="855">Camboya</option>
                                                    <option value="237">Camerún</option>
                                                    <option value="238">Islas de Cabo Verde</option>
                                                    <option value="1(345)">Islas Caimán</option>
                                                    <option value="236">República Centroafricana</option>
                                                    <option value="235">Chad</option>
                                                    <option value="56">Chile</option>
                                                    <option value="86">China</option>
                                                    <option value="57">Colombia</option>
                                                    <option value="269">Comoras</option>
                                                    <option value="243">Congo (DROC), República Democrática del</option>
                                                    <option value="242">Congo (ROC), República de</option>
                                                    <option value="682">Islas Cook</option>
                                                    <option value="506">Costa Rica</option>
                                                    <option value="385">Croacia</option>
                                                    <option value="53">Cuba</option>
                                                    <option value="357">Chipre</option>
                                                    <option value="420">República Checa</option>
                                                    <option value="45">Dinamarca</option>
                                                    <option value="246">Diego García</option>
                                                    <option value="253">Yibuti</option>
                                                    <option value="1(767)">Dominica</option>
                                                    <option value="1(809/829/849)">República Dominicana</option>
                                                    <option value="593">Ecuador</option>
                                                    <option value="20">Egipto</option>
                                                    <option value="503">El Salvador</option>
                                                    <option value="240">Guinea Ecuatorial</option>
                                                    <option value="291">Eritrea</option>
                                                    <option value="1" selected>Estados Unidos de America</option>
                                                    <option value="372">Estonia</option>
                                                    <option value="251">Etiopía</option>
                                                    <option value="500">Islas Malvinas</option>
                                                    <option value="298">Islas Feroe</option>
                                                    <option value="679">Fiyi</option>
                                                    <option value="358">Finlandia</option>
                                                    <option value="33">Francia</option>
                                                    <option value="594">Guyana Francesa</option>
                                                    <option value="241">Gabón</option>
                                                    <option value="220">Gambia</option>
                                                    <option value="995">Georgia</option>
                                                    <option value="49">Alemania</option>
                                                    <option value="233">Ghana</option>
                                                    <option value="350">Gibraltar</option>
                                                    <option value="30">Grecia</option>
                                                    <option value="299">Groenlandia</option>
                                                    <option value="1(473)">Granada</option>
                                                    <option value="590">Guadalupe (Antillas Francesas)</option>
                                                    <option value="502">Guatemala</option>
                                                    <option value="44">Guernsey</option>
                                                    <option value="224">Guinea</option>
                                                    <option value="245">Guinea-Bisáu</option>
                                                    <option value="592">Guyana</option>
                                                    <option value="509">Haití</option>
                                                    <option value="504">Honduras</option>
                                                    <option value="852">Hong Kong</option>
                                                    <option value="36">Hungría</option>
                                                    <option value="354">Islandia</option>
                                                    <option value="91">India</option>
                                                    <option value="62">Indonesia</option>
                                                    <option value="98">Irán</option>
                                                    <option value="964">Iraq</option>
                                                    <option value="353">Irlanda</option>
                                                    <option value="44">Isla de Man</option>
                                                    <option value="972">Israel</option>
                                                    <option value="39">Italia</option>
                                                    <option value="225">Costa de Marfil</option>
                                                    <option value="1(876)">Jamaica</option>
                                                    <option value="81">Japón</option>
                                                    <option value="44">Jersey</option>
                                                    <option value="962">Jordania</option>
                                                    <option value="7">Kazajistán</option>
                                                    <option value="254">Kenia</option>
                                                    <option value="686">Kiribati</option>
                                                    <option value="850">Corea (Norte)</option>
                                                    <option value="82">Corea (Sur)</option>
                                                    <option value="965">Kuwait</option>
                                                    <option value="996">Kirguizistán</option>
                                                    <option value="856">Laos</option>
                                                    <option value="371">Letonia</option>
                                                    <option value="961">Líbano</option>
                                                    <option value="266">Lesoto</option>
                                                    <option value="231">Liberia</option>
                                                    <option value="218">Libia</option>
                                                    <option value="423">Liechtenstein</option>
                                                    <option value="370">Lituania</option>
                                                    <option value="352">Luxemburgo</option>
                                                    <option value="853">Macau</option>
                                                    <option value="389">Macedonia</option>
                                                    <option value="261">Madagascar</option>
                                                    <option value="265">Malaui</option>
                                                    <option value="60">Malasia</option>
                                                    <option value="960">Maldivas</option>
                                                    <option value="223">Malí</option>
                                                    <option value="356">Malta</option>
                                                    <option value="692">Islas Marshall</option>
                                                    <option value="596">Martinica</option>
                                                    <option value="222">Mauritania</option>
                                                    <option value="230">Islas Mauricio</option>
                                                    <option value="52">México</option>
                                                    <option value="691">Micronesia</option>
                                                    <option value="373">Moldova</option>
                                                    <option value="377">Mónaco</option>
                                                    <option value="976">Mongolia</option>
                                                    <option value="382">Montenegro</option>
                                                    <option value="1(664)">Montserrat</option>
                                                    <option value="212">Marruecos</option>
                                                    <option value="258">Mozambique</option>
                                                    <option value="95">Myanmar (Birmania)</option>
                                                    <option value="264">Namibia</option>
                                                    <option value="674">Nauru</option>
                                                    <option value="977">Nepal</option>
                                                    <option value="31">Holanda</option>
                                                    <option value="599">Antillas Neerlandesas (Bonaire, Curacao, Saba, St. Eustis)</option>
                                                    <option value="687">Nueva Caledonia</option>
                                                    <option value="64">Nueva Zelanda</option>
                                                    <option value="505">Nicaragua</option>
                                                    <option value="227">Níger</option>
                                                    <option value="234">Nigeria</option>
                                                    <option value="1(670)">Islas Marianas del Norte</option>
                                                    <option value="47">Noruega</option>
                                                    <option value="968">Omán</option>
                                                    <option value="92">Pakistán</option>
                                                    <option value="680">Palaos</option>
                                                    <option value="970">Autoridad Palestina</option>
                                                    <option value="507">Panamá</option>
                                                    <option value="675">Papúa Nueva Guinea</option>
                                                    <option value="595">Paraguay</option>
                                                    <option value="51">Perú</option>
                                                    <option value="63">Filipinas</option>
                                                    <option value="48">Polonia</option>
                                                    <option value="351">Portugal</option>
                                                    <option value="974">Qatar</option>
                                                    <option value="262">Reunión</option>
                                                    <option value="40">Rumania</option>
                                                    <option value="7">Rusia</option>
                                                    <option value="250">Ruanda</option>
                                                    <option value="1(670)">Saipán (Islas Marianas del Norte)</option>
                                                    <option value="685">Samoa</option>
                                                    <option value="378">San Marino</option>
                                                    <option value="239">Santo Tomé/Príncipe</option>
                                                    <option value="966">Arabia Saudita</option>
                                                    <option value="221">Senegal</option>
                                                    <option value="381">Serbia</option>
                                                    <option value="248">Seychelles</option>
                                                    <option value="232">Sierra Leona</option>
                                                    <option value="65">Singapur</option>
                                                    <option value="1(721)">Isla de San Martín</option>
                                                    <option value="421">Eslovaquia</option>
                                                    <option value="386">Eslovenia</option>
                                                    <option value="677">Islas Salomón</option>
                                                    <option value="27">Sudáfrica</option>
                                                    <option value="211">Sudán Meridional</option>
                                                    <option value="34">España</option>
                                                    <option value="94">Sri Lanka</option>
                                                    <option value="508">San Pedro/Miquelón</option>
                                                    <option value="1(869)">San Cristóbal/Nieves</option>
                                                    <option value="1(758)">Santa Lucía</option>
                                                    <option value="1(784)">San Vicente/Granadinas</option>
                                                    <option value="249">Sudán</option>
                                                    <option value="597">Suriname</option>
                                                    <option value="268">Suazilandia</option>
                                                    <option value="46">Suecia</option>
                                                    <option value="41">Suiza</option>
                                                    <option value="963">Siria</option>
                                                    <option value="886">Taiwán</option>
                                                    <option value="992">Tayikistán</option>
                                                    <option value="255">Tanzania</option>
                                                    <option value="66">Tailandia</option>
                                                    <option value="228">Togo</option>
                                                    <option value="690">Tokelau</option>
                                                    <option value="676">Tonga</option>
                                                    <option value="1(868)">Trinidad y Tobago</option>
                                                    <option value="216">Túnez</option>
                                                    <option value="90">Turquía</option>
                                                    <option value="993">Turkmenistán</option>
                                                    <option value="1(649)">Islas Turcas y Caicos</option>
                                                    <option value="688">Tuvalu</option>
                                                    <option value="256">Uganda</option>
                                                    <option value="380">Ucrania</option>
                                                    <option value="971">Emiratos Árabes Unidos</option>
                                                    <option value="44">Reino Unido</option>
                                                    <option value="598">Uruguay</option>
                                                    <option value="998">Uzbekistán</option>
                                                    <option value="678">Vanuatu</option>
                                                    <option value="58">Venezuela</option>
                                                    <option value="84">Vietnam</option>
                                                    <option value="967">Yemen</option>
                                                    <option value="260">Zambia</option>
                                                    <option value="263">Zimbabue</option>
                                                </select>


                                            </div>
                                            <div class="col-12 col-md-6">
                                                <label for="direccion">N° De Celular Del Cliente</label>
                                                <input type="text" name="direccion" id="direccion" class="form-control" placeholder="N° de Celular" required="">
                                            </div>
                                            <br>
                                            <div class="modal-footer">
                                                <button type="submit" name="btnAgregar" class="btn btn-info"><i class="fas fa-plus-circle"></i> Agregar</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancelar</button>
                                            </div>

                                        </form>
                                    </div>

                                </section>
                            </div>
                        </div>

                    </div>

                    <!-- Modal Formulario Acces Token-->
                    <div class="modal fade" id="Add-access-tokens" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color: #F7A83B; color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Agregar Tokens <i class="fab fa-keycdn"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <section>
                                    <div>
                                        <!--Formulario-->
                                        <form class="row g-3 needs-validation col" id="frmAccesWebToken">
                                            <div class="col-12 col-md-6">
                                                <label for="instancia">Instancia</label>.
                                                <input type="text" name="instancia" id="instancia" class="form-control" placeholder="ejemplo: https://api.chat-api.com/instance123" required="">
                                            </div>
                                            <div class="col-12 col-md-6">
                                                <label for="token">Token</label>
                                                <input type="text" name="token" id="token" class="form-control" placeholder="ejemplo: by711a23eioudz1m0" required="">
                                            </div>




                                            <div class="modal-footer">
                                                <button type="button" name="btnIngresoAccesWebToken" class="btn btn-info" id="btnIngresoAccesWebToken"><i class="fas fa-plus-circle"></i> Agregar</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancelar</button>
                                            </div>
                                            
                                        </form>

                                    </div>

                                </section>

                            </div>
                        </div>

                    </div>

                    <!-- Modal Formulario Plantillas de Mensajes-->
                    <div class="modal body" id="Add-messagess-template" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color: rgb(0,136, 255); color: white">
                                    <h2 class="modal-title" id="exampleModalLongTitle">Agregar Plantillas de Mensajes <i class="fa fa-sticky-note" aria-hidden="true"></i></h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <section>
                                    <div>
                                        <!--Formulario-->
                                        <form action="" method="POST" class="row g-3 needs-validation col" id="Formulario">


                                            <div class="col-12 col-md-6">
                                                <input type="text" class="form-control my-2" value="uno" readonly>
                                                <textarea name="plantillamensajes" class="form-control my-2" id="plantillamensajes" cols="30" rows="10" placeholder="Agregar una Plantilla de Mensaje"></textarea>

                                            </div>
                                            <br>
                                            <div class="modal-footer">
                                                <button type="submit" name="btnAgregar" class="btn btn-info"><i class="fas fa-plus-circle"></i> Agregar</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancelar</button>
                                            </div>

                                        </form>
                                    </div>

                                </section>

                            </div>
                        </div>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>

            <!-- End of Main Content -->