<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Plantillas de Mensajes</h6>
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <form id="areamensajetemplate">
                                    <div class="col-12 col-md-12">
                                        <input type="text" class="form-control my-2" value="<?= $usuario ?>" readonly>
                                        <textarea name="txtMensajeDespedida" class="form-control my-2" id="txtMensajeDespedida" cols="30" rows="10" placeholder="Agregar una Plantilla de Mensaje"></textarea>
                                        <button id="btnIngresarMensajeDespedida" name="btnIngresarMensajeDespedida" class="btn btn-info"><i class="fas fa-plus-circle"></i> Agregar</button>
                                        <button id="btnLimpiarMensajeDespedidad" name="btnLimpiar" class="btn btn-danger"> <i class="fas fa-backspace"></i>  Limpiar</button>
                                    </div>
                                    <br>
                                </form>
                            </div>
                            <div class="col-12 col-sm-8 table-responsive text-center ScrollMinimo" style="overflow:auto; height:300px; width:500px;">
                                <form id="form_MensajeDespedida">
                                    <table class="table table-hover border">
                                        <thead>
                                            <tr>
                                                <th>Mensajes</th>
                                                <th>Fecha Hora</th>
                                                <th>Creador</th>
                                                <th>Accion</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tablaMostrarMensajeDespedida">

                                        </tbody>

                                    </table>

                                </form>
                            </div>
                            
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->