<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h3 class="m-0 font-weight-bold text-primary">Tokens del sistema<button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#user-update" type="button"><i class="fas fa-pencil-alt" aria-hidden="true"></i></button></h3>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Accion</th>
                                            <th>Instancia</th>
                                            <th>Token</th>
                                            <th>Descripcion</th>

                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Accion</th>
                                            <th>Mensaje</th>
                                            <th>Fecha</th>
                                            <th>Hora</th>

                                        </tr>
                                    </tfoot>

                                    <tr>
                                        <td>Michael Bruce</td>
                                        <td>Javascript Developer</td>
                                        <td>Singapore</td>
                                        <td>29</td>


                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->