<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php require_once "app/master/views/template/sidebar.html"; ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php require_once "app/master/views/template/navbar.html"; ?>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="container profile-page">
                        <div class="row">
                            <?php while ($rows = mysqli_fetch_assoc($Resultado)) : ?>
                                <div class="col-xl-6 col-lg-7 col-md-12">
                                    <div class="card profile-header">
                                        <div class="body">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-12">
                                                    <div class="profile-image float-md-right"> <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt=""> </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-12">
                                                    <h4 class="m-t-0 m-b-0"><strong><?= $rows['nombre'] ?> </strong> <?= $rows['apellido'] ?></h4>
                                                    <span class="job_post"> Cargo: </span>
                                                    <p> Direccion :<?= $rows['direccion'] ?></p>
                                                    <p class="" >Rol : ()</p>
                                                    <div>
                                                        <button class="btn btn-primary btn-round">Cambiar Contraseña</button>
                                                        <button class="btn btn-primary btn-round btn-simple">Ver Perfil</button>
                                                    </div>
                                                    <p class="social-icon m-t-5 m-b-0">
                                                        <a title="Twitter" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                                                        <a title="Facebook" href="javascript:void(0);"><i class="fa fa-facebook"></i></a>
                                                        <a title="Google-plus" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                                                        <a title="Behance" href="javascript:void(0);"><i class="fa fa-behance"></i></a>
                                                        <a title="Instagram" href="javascript:void(0);"><i class="fa fa-instagram "></i></a>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            <?php endwhile; ?>

                        </div>


                    </div>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->